# Generated by Django 4.0.2 on 2023-03-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=64)),
                ('basal_cell_carcinomas', models.DecimalField(decimal_places=30, max_digits=31)),
                ('melanoma', models.DecimalField(decimal_places=30, max_digits=31)),
                ('squamous_cell_carcinoma', models.DecimalField(decimal_places=30, max_digits=31)),
            ],
        ),
    ]
